# Generated by Django 5.2.11 on 2026-02-12 12:17

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('id_enquete', models.UUIDField(default=uuid.uuid4, verbose_name='Código')),
                ('titulo', models.CharField(max_length=300, verbose_name='Enquete')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Inicio')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('activa', 'ACTIVA'), ('encerrada', 'ENCERRADA')])),
            ],
            options={
                'verbose_name': 'Enquete',
                'verbose_name_plural': 'Enquetes',
            },
        ),
        migrations.CreateModel(
            name='OpcaoVoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('id_opcao_voto', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('designacao', models.CharField(max_length=255, verbose_name='Opção')),
                ('descricao', models.TextField(verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Opção de Voto',
                'verbose_name_plural': 'Opções de Voto',
            },
        ),
        migrations.CreateModel(
            name='Enquete_Opcao_Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('id_enquete_opcao_voto', models.UUIDField(default=uuid.uuid4)),
                ('id_enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enquete')),
                ('id_opcao_voto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.opcaovoto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('banido', 'Banido')], default='ativo', max_length=10)),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Admin'), ('usuario', 'Usuario')], default='usuario', max_length=10)),
                ('caminho_imagem', models.ImageField(blank=True, null=True, upload_to='images/users/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='enquete',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('id_voto', models.UUIDField(default=uuid.uuid4)),
                ('id_enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enquete')),
                ('id_opcao_voto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.opcaovoto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'unique_together': {('id_enquete', 'id_opcao_voto')},
            },
        ),
    ]
